//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.MVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_User_Log
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Operation { get; set; }
        public string IP { get; set; }
        public string Browser { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
